package io.github.xamdr.noties.ui.helpers

object Constants {
	const val BUNDLE_NOTE_ID = "BUNDLE_NOTE_ID"
	const val BUNDLE_NOTE = "BUNDLE_NOTE"
	const val BUNDLE_TAG_ID = "BUNDLE_TAG_ID"
	const val BUNDLE_SELECTION = "BUNDLE_SELECTION"
	const val BUNDLE_ACTION_MODE = "BUNDLE_ACTION_MODE"
	const val TAG_DIALOG = "TAG_DIALOG"
	const val MENU_DIALOG_TAG = "MENU_DIALOG_TAG"
	const val COLOR_DIALOG_TAG = "COLOR_DIALOG_TAG"
	const val DATE_TIME_PICKER_DIALOG_TAG = "DATE_TIME_PICKER_DIALOG_TAG"
	const val ALT_TEXT_DIALOG_TAG = "ALT_TEXT_DIALOG_TAG"
	const val DELETE_IMAGES_DIALOG_TAG = "DELETE_IMAGES_DIALOG_TAG"
	const val ADD_IMAGES_TAG = "ADD_IMAGES_TAG"
	const val SHARE_CONTENT_TAG = "SHARE_CONTENT_TAG"
	const val IMAGE_STORE_MANAGER = "IMAGE_STORE_MANAGER"
	const val IO = "IO"
	const val REQUEST_KEY = "REQUEST_KEY"
	const val SPAN_COUNT = 2
	const val MIME_TYPE_IMAGE = "image/*"
	const val MIME_TYPE_TEXT = "text/plain"
	const val BUNDLE_RECYCLE_BIN = "BUNDLE_RECYCLE_BIN"
	const val DELETE_NOTES_DIALOG_TAG = "DELETE_NOTES_DIALOG_TAG"
	const val EMPTY_RECYCLE_BIN_DIALOG_TAG = "EMPTY_RECYCLE_BIN_DIALOG_TAG"
}